const tagsList = {
  base: ['wszystko', 'obiady', 'śniadania', 'kawa', 'desery', 'alkohole'],
  dinners: [
    'burgery',
    'pizza',
    'sałatki',
    'makarony',
    'naleśniki',
    'pierogi',
    'zupy',
    'ryby',
    'owoce morza',
    'przystawki',
  ],
  breackfast: ['jajecznica', 'tosty', 'kanapki'],
  desserts: [
    'kawa',
    'ciasta',
    'ciastka',
    'lody',
    'czekolada',
    'shake',
    'koktajle',
    'soki',
    'gofry',
  ],
  alkohol: ['piwo', 'drinki', 'wina', 'rum', 'whisky', 'grzaniec', 'wiśniówka'],
  more: [
    'ogródek',
    'zestawy dla dzieci',
    'zwierzęta',
    'strefa palacza',
    'angielski',
    'niemiecki',
    'bar',
  ],
  cuisine: ['polska', 'europejska', 'orientalna', 'amerykańska', 'włoska'],
};
